name: 'Terraform'
on:
  workflow_dispatch: 
# on:
#   push:
#     branches: [ "develop" ]
env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: .github/workflows
jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5 # Replace with your Terraform version
     
    # - name: Azure login
    #   uses: azure/login@v2
    #   with:
    #     auth-type: IDENTITY
    #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
    #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #     enable-AzPSSession: true
    - name: Azure login
      run: az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password  ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }} 
 

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
          

      # Set environment variables for Terraform
    - name: Set Terraform Environment Variables
      run: |
        echo "ARM_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
        echo "ARM_CLIENT_SECRET=${{ secrets.AZURE_CLIENT_SECRET }}" >> $GITHUB_ENV
        echo "ARM_TENANT_ID=${{ secrets.AZURE_TENANT_ID }}" >> $GITHUB_ENV
        echo "ARM_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV

    # Terraform Init
    - name: Terraform Init
      run: terraform init
      
    # Terraform Plan
    - name: Terraform Plan
      run: terraform plan -out main.tfplan
    # Terraform Apply
    - name: Terraform Apply
      run: terraform apply main.tfplan
